{{- if not .Values.secrets.useExternal }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "veloz.fullname" . }}-api-keys
  labels:
    {{- include "veloz.labels" . | nindent 4 }}
type: Opaque
data:
  binance-api-key: {{ .Values.secrets.inline.binanceApiKey | b64enc | quote }}
  binance-api-secret: {{ .Values.secrets.inline.binanceApiSecret | b64enc | quote }}
{{- end }}
