apiVersion: v1
kind: Service
metadata:
  name: {{ include "veloz.fullname" . }}
  labels:
    {{- include "veloz.labels" . | nindent 4 }}
  {{- with .Values.engine.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.engine.service.type }}
  ports:
    - port: {{ .Values.engine.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "veloz.selectorLabels" . | nindent 4 }}
